spring:
  application:
    name: eureka-service

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

zuul:
  prefix: /api
  routes:
    legacy_api:
      path: /legacy_api/**
      sensitiveHeaders:
      url: http://192.168.32.48:80

    task-service:
      path: /task-service/**
      url: http://192.168.32.48:8503

    wiki-service:
      path: /wiki-service/**
      url: http://192.168.32.38:8500